name: Bug Report
description: Report a bug in GAIA-Server
labels: ["bug", "needs-triage"]
body:
  - type: input
    id: version
    attributes:
      label: Version / commit SHA
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
    validations:
      required: true
